# Generated by Django 6.0.3 on 2026-08-29 10:41

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter your category title', max_length=100, null=True)),
                ('image', models.FileField(blank=True, default='category.jpg', null=True, upload_to='category')),
                ('active', models.BooleanField(default=False, help_text='Activate your account')),
                ('slug', models.SlugField(blank=True, help_text='Enter your slug', max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter your product title', max_length=100, null=True)),
                ('image', models.FileField(blank=True, default='product.jpg', null=True, upload_to='product')),
                ('description', models.TextField(blank=True, help_text='Enter your description', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter your price', max_digits=12, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter your old price', max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Enter your shipping cost', max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=1, help_text='Enter your stock quantity', null=True)),
                ('in_stock', models.BooleanField(default=True, help_text='Is product in stock?')),
                ('featured', models.BooleanField(default=False, help_text='Is product featured?')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ratings', models.PositiveIntegerField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled'), ('in_review', 'In Review')], default='draft', help_text='Select your status', max_length=100, null=True)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', blank=True, length=10, max_length=10, null=True, prefix='', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Enter your slug', max_length=500, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select your category', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
